### ISSUE TITLE
Dictionary in a List

### ISSUE THREAD

**Issue by hs20030238** [snapapps/edgy#281]
Hi guys,
Just now I was trying to retrieve items from dictionary "using for each in a list" block, as shown in the picture, and counter a error.
All items in the list have been set as a dictionary in the same way. If it's retrieved directly it works.
Does somebody have the same issue as well?
![screen shot 2015-05-26 at 12 17 22 pm](https://cloud.githubusercontent.com/assets/12603497/7804128/9e4bf60c-03a1-11e5-9d4b-b074dbc3af1f.png)

**Comment by cyderize** [comment]
That kind of referencing of dictionaries from within a list won't work. Edgy will assume every item in Games List is just a string and not a dictionary (hence dict.get isn't a function).

You put the actual dictionaries inside the list, rather than names, but this means you won't be able to keep the names of the dictionaries:

![dict1](https://cloud.githubusercontent.com/assets/8522468/7808196/e14e539a-03d4-11e5-9f28-36a9e27d8bf6.png)

You can also put the dictionaries inside a dictionary, using their names as keys so you can still have names.

![dict2](https://cloud.githubusercontent.com/assets/8522468/7808198/e2611c36-03d4-11e5-9f6d-b04801513f05.png)

**Comment by stevenbird** [comment]
Thanks @cyderize.
