### ISSUE TITLE
Non-Edgy-specific functionality

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#319]
Identify the functionality that's been added to Edgy that is not specific to graph algorithms, and which should be considered as contributions back to Snap.

**Comment by cyderize** [comment]
I've identified the following pull requests as potentially useful:
#296 + #298 (Exporting of block sequences, warning for dependencies)
#280 + #291 (Possible XSS vulnerability fix)
#271 + #275 (Fix for copying and pasting, since browsers no longer fire events as expected)
#270 (Import/Export of global variables)

**Comment by stevenbird** [comment]
Also: #334 #335

**Comment by stevenbird** [comment]
@brianharvey – would you be interested in PRs for any of the above functionality for Snap?

**Comment by brianharvey** [comment]
Sure, although you really meant @jmoenig :-)

**Comment by jmoenig** [comment]
Sure! thanks!

**Comment by stevenbird** [comment]
OK, thanks @jmoenig, @brianharvey

**Comment by stevenbird** [comment]
@cyderize – would you please rebase this export functionality on Snap and submit PRs there?
* #296 + #298 (Exporting of block sequences, warning for dependencies)
* #270 + #334 + #335 (Import/Export of global variables)

**Comment by stevenbird** [comment]
Closing. Once the newly architected version of Snap we can redesign Edgy as an extension of Snap.
