### ISSUE TITLE
Public APIs for graph data

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#372]
Identify other public APIs which could be interesting sources of graph data

**Comment by cyderize** [comment]
Possible Data APIs
==================
There are a number of possible data APIs that might be of interest.
### [Google Books API](https://developers.google.com/books/)
- We can use this API to search for books or authors and retrieve data (e.g. ISBN, title, author, publish date)
- Data is retrieved through 'volume IDs' which books have - authors don't have IDs
- How this data can be represented as a graph is problematic though - this data source will probably end up like TMDB, with the use of IDs rather than a graph

### [OpenStreetMap API](http://wiki.openstreetmap.org/wiki/API_v0.6)
- There is an example that was made for #77 with graphs of the Melbourne area
- It is also be possible to load data dynamically though, for example, loading a region with a bounding box into the graph
- This might be worth investigating

### [GitHub API](https://developer.github.com/v3)
- Possibilities include:
 - Generating a tree to represent forks of a repository
 - Generating a tree to represent the file structure of a repository
 - Generating a graph to represent followers of users

### A Hyperlink Graph
- Would be useful for PageRank, and hyperlink graphs are intuitive graph representations (in my opinion)
- Possible data sources:
 - http://webdatacommons.org/hyperlinkgraph/
 - https://snap.stanford.edu/data/web-Google.html
 - http://law.di.unimi.it/datasets.php)
- We'd probably have to take a small slice of these graphs because these have hundreds of thousands of nodes

**Comment by stevenbird** [comment]
For the Google Books API, we have agreed on the following method:
```
get_book_info(search terms) -> list of dict  (incl ISBN, author, title, date, publisher)
```
