### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#373]
Georgia Gouros reports the following issue (I haven't tried to replicate it)

![image 2](https://cloud.githubusercontent.com/assets/55406/12318359/b279c556-baed-11e5-8578-7e2a99da5a18.png)

**Comment by cyderize** [comment]
Although #374 fixes this ReferenceError, I've noticed that when adding nodes in a loop like this, the very last node to be added ends up in the wrong position until the graph display is updated (e.g. with `show` or clicking a button). I'm not sure if this is because of something in Edgy or something in JSNetworkX. I'll look into it.

**Comment by stevenbird** [comment]
Well spotted – feel free to open a new issue for this.
