### ISSUE TITLE
Nested Lists issue searching for an item

### ISSUE THREAD

**Issue by GeorgiaG007** [snapapps/edgy#439]
I'm attempting to retrieve an item in a nested list, getting error Type.error list.length is not a function - hope you can see my pasted screenshot image below...
![image](https://cloud.githubusercontent.com/assets/26209779/25831936/bb66283e-34aa-11e7-8b5e-1c87a4f7459e.png)

**Comment by Dalordish** [comment]
You are accessing the first item of the first item of dogs, which is a nested list of 
[[a,b],[b,c][...]]

The block of statements resolves from inner to outer, therefore, the command : length of (item 1 of (item 1 of dogs)) will resolve as follows.

The first item of this list of lists is the list [a,b]
The first item of that list is "a".  
We then attempt to get the length of "a", which returns an type error, although I'm not sure why it returns it as "list.length" is not a function, since the type is clearly not a list but a string.

**Comment by GeorgiaG007** [comment]
thanks Richard, I've tried a new version with testing that the data type is a "text" before recursive call..see attached image and now I get a different error  "Inside: Error reporter didn't report"
![image](https://cloud.githubusercontent.com/assets/26209779/25833134/65016514-34b2-11e7-8b88-75aa85521562.png)

Not sure how to do this?

**Comment by vinita6** [comment]
![edgy-search](https://cloud.githubusercontent.com/assets/26586262/26140177/8f579e02-3b18-11e7-8c16-40b002b7d448.png)

Need to have a report at the end.

**Comment by GeorgiaG007** [comment]
thank you vinita6 for your help
